kind: Ingress
apiVersion: v1
metadata:
  annotations:
    kubernetes.io/elb.id:
    kubernetes.io/elb.ip:
    kubernetes.io/elb.subnet-id:
    kubernetes.io/elb.port: "80"
    kubernetes.io/ingress.class: cce
  name: webapp
spec:
  rules:
  - host: example.com
    http:
      paths:
        - path: /
          backend:
            serviceName: tomcat
            servicePort: 8080